language: node_js
node_js:
  - "10"
  - "12"
python:
  - 2.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

sudo: require

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - sudo pip install pyserial
  - sudo ./scripts/install_smartmeshsdk.sh
  - npm install --unsafe-perm
